---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: roderik.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: roderik.superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: roderik.superlumic-computername

- src: https://github.com/superlumic/ansible-role-mysql.git
  name: roderik.superlumic-mysql

- src: https://github.com/superlumic/ansible-role-php.git
  name: roderik.superlumic-php

- src: https://github.com/superlumic/ansible-role-node.git
  name: roderik.superlumic-node
