
---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - flux
        - harvest

  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: testbookpro
    - git_user_name: Test Test
    - git_user_email: test@wijs.be
    - osx_defaults:
      ##########################################################################
      # General OS X settings
      ##########################################################################
      # Always show scrollbars
      # Possible values: `WhenScrolling`, `Automatic` and `Always`
      - domain: 'NSGlobalDomain'
        key: 'AppleShowScrollBars'
        type: string
        value: 'always'
      # Disable transparency in the menu bar and elsewhere on Yosemite
      - domain: 'com.apple.universalaccess'
        key: 'reduceTransparency'
        type: boolean
        value: true
      # Set highlight color to green
      - domain: 'NSGlobalDomain'
        key: 'AppleHighlightColor'
        type: string
        value: '0.764700 0.976500 0.568600'
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: right
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
