
---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - adobe-creative-cloud
        - appcleaner
        - caffeine
        - calibre
        - dash
        - deluge
        - disk-inventory-x
        - dropbox
        - filezilla
        - firefox
        - flux
        - harvest
        - istat-menus
        - macdown
        - microsoft-office365
        - mplayerx
        - mysqlworkbench
        - plex-home-theater
        - skitch
        - skype
        - slack
        - spotify
        - teamviewer
        - telegram
        - vlc
        - vagrant
        # these should be either in the profile-all or profile-developer
        # configs but let's check anyway
        - hipchat
        - google-chrome
        - google-drive
        - lastpass
        - iterm2
        - phpstorm
        - sequel-pro
        - iterm2

    # - name: add to sudoers without password
    #   become: yes
    #   lineinfile: >
    #     dest=/etc/sudoers
    #     regexp="{{ item.regexp }}"
    #     line="{{ item.line }}"
    #     state=present
    #     create=true
    #   with_items:
    #     - { regexp: '^tom', line: 'tom ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: mbptb
    - git_user_name: Tom Bernaerd
    - git_user_email: tom@bernaerd.be
    - osx_defaults:
      # Always show scrollbars
      # Possible values: `WhenScrolling`, `Automatic` and `Always`
      - domain: 'NSGlobalDomain'
        key: 'AppleShowScrollBars'
        type: string
        value: 'always'
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: right
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      - domain: 'NSGlobalDomain'
        key: 'ApplePressAndHoldEnabled'
        type: boolean
        value: false
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
