
---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
#        - adobe-creative-cloud
        - appcleaner
        - caffeine
        - calibre
        - dash
        - deluge
        - disk-inventory-x
        - dropbox
        - filezilla
        - firefox
        - flux
        - harvest
        - istat-menus
        - macdown
#        - microsoft-office365
        - mplayerx
        - mysqlworkbench
        - plex-home-theater
        - skitch
        - skype
        - slack
        - spotify
        - teamviewer
        - telegram
        - vlc
        - vagrant
        # these should be either in the profile-all or profile-developer
        # configs but let's check anyway
        - hipchat
        - google-chrome
        - google-drive
        - lastpass
        - iterm2
#        - phpstorm
        - sequel-pro
        - iterm2
        - atom
# this one assumes my username is tom, change it to yours
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^tom', line: 'tom ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: mbptb
    - git_user_name: Tom Bernaerd
    - git_user_email: tom@bernaerd.be
    - osx_defaults:
      ##########################################################################
      # General OS X settings
      ##########################################################################
      # Always show scrollbars
      # Possible values: `WhenScrolling`, `Automatic` and `Always`
      - domain: 'NSGlobalDomain'
        key: 'AppleShowScrollBars'
        type: string
        value: 'always'
      # Disable transparency in the menu bar and elsewhere on Yosemite
      - domain: 'com.apple.universalaccess'
        key: 'reduceTransparency'
        type: boolean
        value: true
      # Set highlight color to green
      - domain: 'NSGlobalDomain'
        key: 'AppleHighlightColor'
        type: string
        value: '0.764700 0.976500 0.568600'
      # Dock: Size
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      # Dock: instant autohide
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      # Dock: instant autohide
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      # Dock: autohide
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      # Dock: minimize to application instead of to the right
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      # Dock: process indicators. Useful when PHPStorm is overthinking things
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      # Dock: on the bottom
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
      # Finder: small icons in sidebar
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      # Faster key repeat
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      # Faster initial key repeat
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      # Clock: date and time format
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      # Battery: show percentage
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      # Finder: show list style
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      # Save mode: always expanded
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      #
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      # Touchpad: press and hold enabled
      - domain: 'NSGlobalDomain'
        key: 'ApplePressAndHoldEnabled'
        type: boolean
        value: false
      # Don't write .DS_store crap to network stores
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      # Printing: quit when finished
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
      # Printing: always expanded
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
