---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - coreutils
    - moreutils
    - findutils
    - bash
    - zsh
    - wget
    - pwgen
    - htop-osx
    - watch
    - rsync
    - git-flow
    - mtr
    - mosh
    - ack
    - imagemagick
    - nmap
    - rename
    - tig
    - hub

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - phpstorm
    - sequel-pro
    - iterm2
